In [1]:
from sklearn.datasets import make_blobs
from scipy.stats import norm
from numpy import mean,std


In [6]:
X,y=make_blobs(n_samples=100,centers=2,n_features=2, random_state=1)

In [7]:
X

array([[-7.94152277e-01,  2.10495117e+00],
       [-9.15155186e+00, -4.81286449e+00],
       [-3.10367371e+00,  3.90202401e+00],
       [-1.42946517e+00,  5.16850105e+00],
       [-7.46938680e+00, -4.20198333e+00],
       [-9.19585147e+00, -3.90678125e+00],
       [-9.31764266e+00, -4.27315015e+00],
       [-9.20490564e+00, -4.57687928e+00],
       [-2.76017908e+00,  5.55121358e+00],
       [-1.17104176e+00,  4.33091816e+00],
       [-1.00364080e+01, -5.56912090e+00],
       [-1.53773863e+00,  5.53597378e+00],
       [-1.01081595e+01, -4.57071061e+00],
       [-2.40671820e+00,  6.09894447e+00],
       [-7.80701277e+00, -5.84970947e+00],
       [-9.01137732e+00, -3.73981465e+00],
       [-9.76521794e+00, -3.27079714e+00],
       [-2.34673261e+00,  3.56128423e+00],
       [-2.00341358e+00,  4.45008673e+00],
       [-1.10926243e+01, -3.78396611e+00],
       [-9.43495141e+00, -3.71261146e+00],
       [-1.02639310e+01, -3.92073400e+00],
       [-9.74891334e+00, -4.24998970e+00],
       [-1.

In [8]:
y

array([0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0])

In [9]:
# calculate priors 

Xy0=X[y==0]
Xy0

array([[-7.94152277e-01,  2.10495117e+00],
       [-3.10367371e+00,  3.90202401e+00],
       [-1.42946517e+00,  5.16850105e+00],
       [-2.76017908e+00,  5.55121358e+00],
       [-1.17104176e+00,  4.33091816e+00],
       [-1.53773863e+00,  5.53597378e+00],
       [-2.40671820e+00,  6.09894447e+00],
       [-2.34673261e+00,  3.56128423e+00],
       [-2.00341358e+00,  4.45008673e+00],
       [-1.34052081e+00,  4.15711949e+00],
       [-2.03484486e+00,  3.76775946e+00],
       [-1.35938959e+00,  4.05424002e+00],
       [-1.97451969e-01,  2.34634916e+00],
       [-1.92744799e+00,  4.93684534e+00],
       [-2.80207810e+00,  4.05714715e+00],
       [-1.85139546e+00,  3.51886090e+00],
       [-4.60642026e-01,  4.59164629e+00],
       [-1.98197711e+00,  4.02243551e+00],
       [-1.46126019e+00,  4.52549851e+00],
       [-7.57969185e-01,  4.90898421e+00],
       [ 5.26015501e-01,  3.00999353e+00],
       [-2.77687025e+00,  4.64090557e+00],
       [-1.78245013e+00,  3.47072043e+00],
       [-1.

In [10]:
Xy1=X[y==1]
Xy1

array([[ -9.15155186,  -4.81286449],
       [ -7.4693868 ,  -4.20198333],
       [ -9.19585147,  -3.90678125],
       [ -9.31764266,  -4.27315015],
       [ -9.20490564,  -4.57687928],
       [-10.03640801,  -5.5691209 ],
       [-10.10815953,  -4.57071061],
       [ -7.80701277,  -5.84970947],
       [ -9.01137732,  -3.73981465],
       [ -9.76521794,  -3.27079714],
       [-11.09262435,  -3.78396611],
       [ -9.43495141,  -3.71261146],
       [-10.26393101,  -3.920734  ],
       [ -9.74891334,  -4.2499897 ],
       [-10.30782928,  -6.38818631],
       [ -9.55634806,  -4.05350378],
       [ -9.47713617,  -5.09768994],
       [-10.51480696,  -4.95037538],
       [ -8.37006175,  -3.61533685],
       [-10.18428228,  -4.05509442],
       [-11.37082982,  -3.63818916],
       [-10.17863281,  -4.55726918],
       [-10.13415725,  -4.07240274],
       [ -9.71704743,  -4.02646125],
       [ -9.64716652,  -5.26563196],
       [-11.22777064,  -3.40281105],
       [ -9.46824718,  -3.81564734],
 

In [12]:
print(Xy0.shape,Xy1.shape)

(50, 2) (50, 2)


In [15]:
priory0=len(Xy0)/len(X)
priory1=len(Xy1)/len(X)

In [16]:
print(priory0,priory1)

0.5 0.5


In [27]:
def fit_distribution(data):
    mu=mean(data)
    sigma=std(data)
    
    #print(mu,sigma)
    dist=norm(mu,sigma)
    return dist
    

In [24]:
fit_distribution(Xy1[:,0])

-9.681177100524485 0.8943078901048118


In [29]:
X1y0=fit_distribution(Xy0[:,0])
X2y0=fit_distribution(Xy0[:,1])
X1y1=fit_distribution(Xy1[:,0])
X2y1=fit_distribution(Xy1[:,1])

In [30]:
def prob(X,prior,dist1,dist2):
    return prior*dist1.pdf(X[0])*dist2.pdf(X[1])

In [31]:
#classify one example
Xsample,ysample=X[0],y[0]
print(Xsample,ysample)

[-0.79415228  2.10495117] 0


In [35]:
py0=prob(Xsample,priory0,X1y0,X2y0)
py1=prob(Xsample,priory1,X1y1,X2y1)
print(py0,py1)

0.0034776913685206174 1.9210297039631055e-32


In [36]:
if py1>py0:
    print(1)
else:
    print(0)

0
